# Generated by Django 3.1.4 on 2020-12-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=7)),
                ('descricao', models.CharField(max_length=500)),
                ('cred_aula', models.IntegerField()),
                ('cred_trabalho', models.IntegerField()),
                ('ch_total', models.IntegerField()),
                ('programa_resumido', models.CharField(max_length=300)),
                ('met_avaliacao', models.CharField(max_length=50)),
                ('crit_avaliacao', models.CharField(max_length=50)),
                ('recup_avaliacao', models.CharField(max_length=50)),
                ('bibliografia', models.CharField(max_length=1000)),
            ],
        ),
    ]
