# Generated by Django 3.1.4 on 2020-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='bibliografia',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='programa_resumido',
            field=models.TextField(max_length=300),
        ),
    ]
