# Generated by Django 3.1.4 on 2020-12-12 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='downVote',
        ),
        migrations.AddField(
            model_name='comentario',
            name='downVote',
            field=models.ManyToManyField(blank=True, related_name='downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='upVote',
        ),
        migrations.AddField(
            model_name='comentario',
            name='upVote',
            field=models.ManyToManyField(blank=True, related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
