# Generated by Django 3.1.4 on 2020-12-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20201212_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notageral', models.FloatField(default=0)),
                ('notaCrit1', models.FloatField(default=0)),
                ('notaCrit2', models.FloatField(default=0)),
                ('notaCrit3', models.FloatField(default=0)),
                ('notaCrit4', models.FloatField(default=0)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disciplina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
