# Generated by Django 3.1.4 on 2020-12-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201212_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='notaCrit1',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='notaCrit2',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='notaCrit3',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='notaCrit4',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='notageral',
        ),
    ]
