# Generated by Django 3.1.4 on 2020-12-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
