# Generated by Django 3.1.4 on 2020-12-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201213_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='met_avaliacao',
            field=models.TextField(null=True),
        ),
    ]
